apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-development
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      - app: app
  template:
    - metadata:
        labels:
          app: app
    - spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 80
